# Generated by Django 5.0 on 2023-12-11 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_paymentmod_upi'),
        ('store', '0006_delete_contact_users'),
    ]

    operations = [
    ]
